version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
